n = int(input())
sizes = list(map(int, input().split()))
t, p = map(int, input().split())
shirt_bundles = sum((size + t - 1) // t for size in sizes)
pen_bundles, pen_singles = divmod(n, p)
print(shirt_bundles)
print(pen_bundles, pen_singles)